services:

  postgres:
    container_name: postgres-microservices
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db-net
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-microservices
    ports:
      - "9411:9411"
    networks:
      - zipkin-net

  vault-server:
    image: vault:latest
    container_name: vault-microservices
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "00000000-0000-0000-0000-000000000000"

  # username:guest pw:guest
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq-microservices
    ports:
      - "5672:5672"
      - "15672:15672"

  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: "zookeeper-microservices"
    ports:
      - "2181:2181"
    environment:
     ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka:latest
    container_name: "kafka-microservices"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
     KAFKA_BROKER_ID: 1
     KAFKA_LISTENERS: PLAINTEXT://:9092
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     ALLOW_PLAINTEXT_LISTENER: yes


#  keycloak:
#    depends_on:
#      - postgres
#    container_name: "keycloak-microservices"
#    environment:
#      DB_VENDOR: postgres
#      DB_ADDR: postgres
#      DB_DATABASE: keycloak
#      DB_USER: postgres
#      DB_PASSWORD: 1
#      KEYCLOAK_USER: umurinan
#      KEYCLOAK_PASSWORD: 1
#    image: jboss/keycloak:latest
#    ports:
#      - "28080:8080"
#    restart: unless-stopped
#    networks:
#      - db-net



#  config-server:
#    image: umurinan/config-server:1.0.0
#    container_name: config-server
#    ports:
#      - "9090:9090"
#    networks:
#      - config-server-net
#
#  service-discovery:
#    image: umurinan/service-discovery:1.0.0
#    container_name: service-discovery
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - config-server
#      - zipkin
#    networks:
#      - config-server-net
#    restart: unless-stopped
#
#  user:
#    image: umurinan/user-service:1.0.0
#    container_name: user-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - config-server
#      - zipkin
#      - postgres
#    networks:
#      - config-server-net
#      - db-net
#      - zipkin-net
#    restart: unless-stopped



networks:

  db-net:
    driver: bridge

  zipkin-net:
    driver: bridge
    name: microservices-zipkin

  spring:
    driver: bridge

  config-server-net:
    driver: bridge
    name: microservices-config-server


volumes:
  postgres:
  pgadmin: