spring:
  profiles:
    active: docker

---

spring:
  application:
    name: service-discovery
  config:
    import: optional:configserver:http://localhost:9090
    activate:
      on-profile: dev

---

spring:
  application:
    name: service-discovery
  config:
    import: optional:configserver:http://config-server-net:9090
    activate:
      on-profile: docker


#spring:
#  application:
#    name: service-discovery
#  config:
#    import: optional:configserver:http://localhost:9090