version: 2.1

jobs:

  build-and-install:

    docker:
      - image: cimg/openjdk:17.0.2

    steps:
      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: Install
          command: mvn install

workflows:
  sample: 
    jobs:
      - build-and-install
