spring:
  application:
    name: cloud-gateway
#  boot:
#    admin:
#      client:
#        url: http://localhost:8093
  #  cloud:
  #    gateway:
  #      routes:
  #        - id: user-service
  #          uri: lb://user
  #          predicates:
  #            - Path=/users/**

#  cloud:
#    gateway:
#      discovery:
#        locater:
#          enabled: true
#          lower-case-service-id : true



eureka:
#  client:
#    healthcheck:
#      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: ALWAYS

