spring:
  application:
    name: cloud-gateway

eureka:
#  client:
#    healthcheck:
#      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: ALWAYS

