server:
  port: 8093

spring:
  application:
    name: admin

#  boot:
#    admin:
#      client:
#        url=http://localhost:8093
#
#  management:
#    endpoints:
#      web:
#        exposure:
#          include: "*"
#    health:
#      show-details: always